name: Publish Python 🐍 package to PyPI

on:
  push:
    branches:
      - main  # Or your default branch
    tags:
      - 'v*'  # This assumes your tag names follow semantic versioning

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
      - name: Install poetry
        run: pip install poetry
        
      - name: Configure poetry
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
        
      - name: Build and publish
        run: poetry publish --build

