name: Publish Python Package

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Set this to your Python version

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Configure Poetry
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install Dependencies
      run: poetry install

    - name: Increment Version
      run: poetry version patch

    - name: Build Package
      run: poetry build


    - name: Build Package
      run: |
        python setup.py sdist bdist_wheel

    # Uncomment the following steps to publish your package to PyPI
    - name: Publish to PyPI
     uses: pypa/gh-action-pypi-publish@master
     with:
       user: __token__
       password: ${{ secrets.PYPI_API_TOKEN }}
